/**
 * Oracle ERP Cloud Fusion & Oracle Database SQL Exporter Service
 * مولد ملفات الترحيل الرسمية (Oracle FBDI / WebADI) وكود قاعدة بيانات أوراكل SQL
 */

import { OracleJournalBatch, OracleAccountingPeriod, OracleLedger } from '../types/oracle';
import { DatabaseState } from '../db/localDatabase';

export class OracleExportService {
  /**
   * توليد ملف GL_INTERFACE المتوافق 100% مع واجهة استيراد أوراكل الرسمية
   */
  static generateFBDI_GLInterfaceCSV(batches: OracleJournalBatch[], ledger: OracleLedger): string {
    const headers = [
      'STATUS',
      'LEDGER_ID',
      'ACCOUNTING_DATE',
      'CURRENCY_CODE',
      'USER_JE_SOURCE_NAME',
      'USER_JE_CATEGORY_NAME',
      'SEGMENT1_COMPANY',
      'SEGMENT2_COST_CENTER',
      'SEGMENT3_ACCOUNT',
      'SEGMENT4_SUB_ACCOUNT',
      'SEGMENT5_INTERCOMPANY',
      'ENTERED_DR',
      'ENTERED_CR',
      'ACCOUNTED_DR',
      'ACCOUNTED_CR',
      'REFERENCE1_BATCH_NAME',
      'REFERENCE4_LINE_DESC',
      'REFERENCE10_PERIOD_NAME',
      'GROUP_ID',
    ];

    const rows: string[] = [headers.join(',')];

    batches.forEach((batch, batchIdx) => {
      const groupId = 1000 + batchIdx;
      batch.lines.forEach((line) => {
        const row = [
          'NEW',
          `"${ledger.id}"`,
          batch.accountingDate,
          `"${line.enteredCurrency}"`,
          `"${batch.source}"`,
          `"${batch.category}"`,
          `"${line.companyCode}"`,
          `"${line.costCenterCode}"`,
          `"${line.accountCode}"`,
          `"${line.subAccountCode}"`,
          `"${line.intercompanyCode}"`,
          line.enteredDebit || '',
          line.enteredCredit || '',
          line.accountedDebit || '',
          line.accountedCredit || '',
          `"${batch.batchName.replace(/"/g, '""')}"`,
          `"${line.lineDescription.replace(/"/g, '""')}"`,
          `"${batch.periodName}"`,
          groupId,
        ];
        rows.push(row.join(','));
      });
    });

    return rows.join('\n');
  }

  /**
   * توليد سكريبت إنشاء قاعدة بيانات أوراكل كاملة (Oracle 19c/21c DDL & PL/SQL Packages)
   */
  static generateOracleDatabaseSchemaSQL(state: DatabaseState): string {
    return `--------------------------------------------------------
-- ORACLE DATABASE 19c / 21c ENTERPRISE FINANCIALS SCHEMA
-- نظام المحاسب القانوني ومراقب الحسابات - المخطط المحاسبي المتوافق مع أوراكل
-- Generated: ${new Date().toISOString()}
--------------------------------------------------------

-- 1. DROP EXISTING OBJECTS (CLEAN SLATE)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE GL_JE_LINES CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE GL_JE_BATCHES CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE GL_PERIOD_STATUSES CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE GL_LEDGERS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE GL_CODE_COMBINATIONS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE AP_INVOICES_ALL CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE AR_TRANSACTIONS_ALL CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- 2. CREATE CODE COMBINATIONS TABLE (FLEXFIELD SEGMENTS)
CREATE TABLE GL_CODE_COMBINATIONS (
    CODE_COMBINATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SEGMENT1_COMPANY VARCHAR2(10) NOT NULL,
    SEGMENT2_COST_CENTER VARCHAR2(10) NOT NULL,
    SEGMENT3_ACCOUNT VARCHAR2(20) NOT NULL,
    SEGMENT4_SUB_ACCOUNT VARCHAR2(10) DEFAULT '000',
    SEGMENT5_INTERCOMPANY VARCHAR2(10) DEFAULT '00',
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL, -- ASSETS, LIABILITIES, EQUITY, REVENUE, EXPENSE
    ENABLED_FLAG VARCHAR2(1) DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y','N')),
    ACCOUNT_NAME_AR VARCHAR2(200) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT UK_GL_COMBINATION UNIQUE (SEGMENT1_COMPANY, SEGMENT2_COST_CENTER, SEGMENT3_ACCOUNT, SEGMENT4_SUB_ACCOUNT, SEGMENT5_INTERCOMPANY)
);

-- 3. CREATE LEDGERS TABLE
CREATE TABLE GL_LEDGERS (
    LEDGER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    SHORT_NAME VARCHAR2(30) NOT NULL,
    CURRENCY_CODE VARCHAR2(5) NOT NULL,
    LEDGER_CATEGORY_CODE VARCHAR2(20) NOT NULL, -- PRIMARY, SECONDARY, REPORTING
    ACCOUNTING_STANDARD VARCHAR2(20) DEFAULT 'EAS',
    PERIOD_SET_NAME VARCHAR2(50) DEFAULT 'MONTHLY_CALENDAR',
    IS_ACTIVE VARCHAR2(1) DEFAULT 'Y'
);

-- 4. CREATE PERIOD STATUSES TABLE
CREATE TABLE GL_PERIOD_STATUSES (
    PERIOD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LEDGER_ID NUMBER REFERENCES GL_LEDGERS(LEDGER_ID),
    PERIOD_NAME VARCHAR2(20) NOT NULL,
    PERIOD_NAME_AR VARCHAR2(50) NOT NULL,
    PERIOD_YEAR NUMBER(4) NOT NULL,
    PERIOD_NUM NUMBER(2) NOT NULL,
    QUARTER_NUM VARCHAR2(5) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CLOSING_STATUS VARCHAR2(20) DEFAULT 'OPEN' CHECK (CLOSING_STATUS IN ('OPEN', 'CLOSED', 'PERMANENTLY_CLOSED', 'FUTURE_ENTERABLE')),
    CONSTRAINT UK_LEDGER_PERIOD UNIQUE (LEDGER_ID, PERIOD_NAME)
);

-- 5. CREATE JOURNAL BATCHES & HEADERS TABLE
CREATE TABLE GL_JE_BATCHES (
    JE_BATCH_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LEDGER_ID NUMBER REFERENCES GL_LEDGERS(LEDGER_ID),
    NAME VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(300),
    PERIOD_NAME VARCHAR2(20) NOT NULL,
    ACCOUNTING_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'UNPOSTED' CHECK (STATUS IN ('UNPOSTED', 'POSTED', 'FUNDS_CHECKED', 'REVERSED')),
    POSTED_DATE DATE,
    POSTED_BY VARCHAR2(100),
    TOTAL_DR NUMBER(18,2) DEFAULT 0,
    TOTAL_CR NUMBER(18,2) DEFAULT 0,
    CREATION_DATE DATE DEFAULT SYSDATE
);

-- 6. CREATE JOURNAL LINES TABLE
CREATE TABLE GL_JE_LINES (
    JE_LINE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JE_BATCH_ID NUMBER REFERENCES GL_JE_BATCHES(JE_BATCH_ID) ON DELETE CASCADE,
    JE_LINE_NUM NUMBER NOT NULL,
    CODE_COMBINATION_ID NUMBER REFERENCES GL_CODE_COMBINATIONS(CODE_COMBINATION_ID),
    ENTERED_CURRENCY VARCHAR2(5) DEFAULT 'EGP',
    ENTERED_DR NUMBER(18,2) DEFAULT 0,
    ENTERED_CR NUMBER(18,2) DEFAULT 0,
    ACCOUNTED_DR NUMBER(18,2) DEFAULT 0,
    ACCOUNTED_CR NUMBER(18,2) DEFAULT 0,
    EXCHANGE_RATE NUMBER(12,6) DEFAULT 1.0,
    DESCRIPTION VARCHAR2(300)
);

-- 7. PL/SQL PACKAGE FOR BALANCED POSTING VALIDATION
CREATE OR REPLACE PACKAGE PKG_ORACLE_GL_POSTING AS
    PROCEDURE POST_BATCH(p_batch_id IN NUMBER, p_user_name IN VARCHAR2, p_status OUT VARCHAR2, p_message OUT VARCHAR2);
    PROCEDURE CHECK_FUNDS(p_batch_id IN NUMBER, p_result OUT VARCHAR2);
END PKG_ORACLE_GL_POSTING;
/

CREATE OR REPLACE PACKAGE BODY PKG_ORACLE_GL_POSTING AS
    PROCEDURE CHECK_FUNDS(p_batch_id IN NUMBER, p_result OUT VARCHAR2) IS
        v_total_dr NUMBER;
        v_total_cr NUMBER;
    BEGIN
        SELECT NVL(SUM(ACCOUNTED_DR),0), NVL(SUM(ACCOUNTED_CR),0)
        INTO v_total_dr, v_total_cr
        FROM GL_JE_LINES
        WHERE JE_BATCH_ID = p_batch_id;

        IF ABS(v_total_dr - v_total_cr) < 0.01 THEN
            p_result := 'PASSED';
        ELSE
            p_result := 'FAILED_OUT_OF_BALANCE';
        END IF;
    END CHECK_FUNDS;

    PROCEDURE POST_BATCH(p_batch_id IN NUMBER, p_user_name IN VARCHAR2, p_status OUT VARCHAR2, p_message OUT VARCHAR2) IS
        v_funds_status VARCHAR2(30);
        v_period_status VARCHAR2(20);
        v_period_name VARCHAR2(20);
        v_ledger_id NUMBER;
    BEGIN
        -- Check Balance
        CHECK_FUNDS(p_batch_id, v_funds_status);
        IF v_funds_status != 'PASSED' THEN
            p_status := 'ERROR';
            p_message := 'القيد غير متزن محاسبياً (إجمالي المدين لا يساوي الدائن)';
            RETURN;
        END IF;

        -- Check Period Open status
        SELECT PERIOD_NAME, LEDGER_ID INTO v_period_name, v_ledger_id FROM GL_JE_BATCHES WHERE JE_BATCH_ID = p_batch_id;
        SELECT CLOSING_STATUS INTO v_period_status FROM GL_PERIOD_STATUSES WHERE LEDGER_ID = v_ledger_id AND PERIOD_NAME = v_period_name;

        IF v_period_status != 'OPEN' THEN
            p_status := 'ERROR';
            p_message := 'لا يمكن الترحيل لأن الفترة المالية ' || v_period_name || ' مغلقة';
            RETURN;
        END IF;

        -- Update Batch to Posted
        UPDATE GL_JE_BATCHES
        SET STATUS = 'POSTED',
            POSTED_DATE = SYSDATE,
            POSTED_BY = p_user_name
        WHERE JE_BATCH_ID = p_batch_id;

        p_status := 'SUCCESS';
        p_message := 'تم ترحيل الدفعة المحاسبية بنجاح إلى دفتر الأستاذ العام بأوراكل';
    END POST_BATCH;
END PKG_ORACLE_GL_POSTING;
/

-- 8. INSERT INITIAL SEED DATA (LEDGERS & PRIMARY COMBINATIONS)
INSERT INTO GL_LEDGERS (LEDGER_ID, NAME, SHORT_NAME, CURRENCY_CODE, LEDGER_CATEGORY_CODE, ACCOUNTING_STANDARD)
VALUES (1, 'دفتر الأستاذ العام بالجنيه المصري (معايير EAS)', 'EAS_EGP_PL', 'EGP', 'PRIMARY', 'EAS');

INSERT INTO GL_LEDGERS (LEDGER_ID, NAME, SHORT_NAME, CURRENCY_CODE, LEDGER_CATEGORY_CODE, ACCOUNTING_STANDARD)
VALUES (2, 'دفتر تقارير المعايير الدولية IFRS (بالدولار الأمريكي)', 'IFRS_USD_SL', 'USD', 'SECONDARY', 'IFRS');

COMMIT;
`;
  }
}
