import React from 'react';
import {
  BookOpen,
  FileCheck2,
  Receipt,
  ShieldCheck,
  FileSpreadsheet,
  Percent,
  Building2,
  TrendingUp,
  Sparkles,
  Layers,
  Scale,
  CheckCircle2,
  Smartphone,
  LayoutDashboard,
  Shield,
  Folder,
} from 'lucide-react';

export interface ScreenMetadata {
  tabKey: string;
  titleAr: string;
  titleEn: string;
  categoryAr: string;
  categoryEn: string;
  icon: React.ElementType;
}

export const SCREEN_METADATA_REGISTRY: Record<string, ScreenMetadata> = {
  DASHBOARD: {
    tabKey: 'DASHBOARD',
    titleAr: 'لوحة القيادة والمؤشرات العامة',
    titleEn: 'Executive Dashboard',
    categoryAr: 'الرئيسية والمؤشرات',
    categoryEn: 'Core Dashboard',
    icon: LayoutDashboard,
  },
  JOURNAL_ENTRIES: {
    tabKey: 'JOURNAL_ENTRIES',
    titleAr: 'قيود اليومية العامة',
    titleEn: 'General Journal Entries',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: BookOpen,
  },
  CHART_OF_ACCOUNTS: {
    tabKey: 'CHART_OF_ACCOUNTS',
    titleAr: 'دليل وشجرة الحسابات المصرية',
    titleEn: 'Egyptian Chart of Accounts',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: Layers,
  },
  GENERAL_LEDGER: {
    tabKey: 'GENERAL_LEDGER',
    titleAr: 'دفتر الأستاذ العام',
    titleEn: 'General Ledger',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: Receipt,
  },
  TRIAL_BALANCE: {
    tabKey: 'TRIAL_BALANCE',
    titleAr: 'ميزان المراجعة بالأرصدة والمجاميع',
    titleEn: 'Trial Balance',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: Scale,
  },
  FIXED_ASSETS: {
    tabKey: 'FIXED_ASSETS',
    titleAr: 'سجل الأصول الثابتة والإهلاك (معيار 10)',
    titleEn: 'Fixed Assets (EAS 10)',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: Building2,
  },
  BANK_RECONCILIATION: {
    tabKey: 'BANK_RECONCILIATION',
    titleAr: 'مذكرة التسوية البنكية والمطابقة',
    titleEn: 'Bank Reconciliation',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: CheckCircle2,
  },
  CURRENCY_EXCHANGE_RATES: {
    tabKey: 'CURRENCY_EXCHANGE_RATES',
    titleAr: 'أسعار الصرف اليومية (EAS 13)',
    titleEn: 'Daily Exchange Rates',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: TrendingUp,
  },
  OCR_INVOICE_SCANNER: {
    tabKey: 'OCR_INVOICE_SCANNER',
    titleAr: 'مسح واستخراج الفواتير بالذكاء الاصطناعي (OCR)',
    titleEn: 'OCR Invoice Scanner',
    categoryAr: 'العمليات المحاسبية',
    categoryEn: 'Accounting & Journals',
    icon: Sparkles,
  },
  CERTIFICATES: {
    tabKey: 'CERTIFICATES',
    titleAr: 'الشهادات المهنية المعتمدة',
    titleEn: 'Certified Income Attestations',
    categoryAr: 'الشهادات والاعتمادات',
    categoryEn: 'Certificates',
    icon: FileCheck2,
  },
  FEASIBILITY_STUDY: {
    tabKey: 'FEASIBILITY_STUDY',
    titleAr: 'دراسات الجدوى الاقتصادية',
    titleEn: 'Feasibility Studies',
    categoryAr: 'الشهادات والاعتمادات',
    categoryEn: 'Certificates',
    icon: TrendingUp,
  },
  INVOICING: {
    tabKey: 'INVOICING',
    titleAr: 'الفواتير والمطالبات وأتعاب المراجعة',
    titleEn: 'Invoicing & Claims',
    categoryAr: 'الفواتير والضرائب',
    categoryEn: 'Invoicing & Tax',
    icon: Receipt,
  },
  ETA_RECONCILIATION: {
    tabKey: 'ETA_RECONCILIATION',
    titleAr: 'مطابقة الفاتورة الإلكترونية مع منظومة ETA',
    titleEn: 'ETA E-Invoice Reconciliation',
    categoryAr: 'الفواتير والضرائب',
    categoryEn: 'Invoicing & Tax',
    icon: CheckCircle2,
  },
  TAX_TRACKER: {
    tabKey: 'TAX_TRACKER',
    titleAr: 'أجندة الالتزامات والإقرارات الضريبية',
    titleEn: 'Tax Declarations Tracker',
    categoryAr: 'الفواتير والضرائب',
    categoryEn: 'Invoicing & Tax',
    icon: Percent,
  },
  TAX_PENALTY_SIMULATOR: {
    tabKey: 'TAX_PENALTY_SIMULATOR',
    titleAr: 'محاكي مقابل التأخير والغرامات الضريبية',
    titleEn: 'Tax Penalties Simulator',
    categoryAr: 'الفواتير والضرائب',
    categoryEn: 'Invoicing & Tax',
    icon: Percent,
  },
  PAYROLL_INSURANCE: {
    tabKey: 'PAYROLL_INSURANCE',
    titleAr: 'كسب العمل والتأمينات الاجتماعية (قانون 148)',
    titleEn: 'Payroll & Social Insurance',
    categoryAr: 'الفواتير والضرائب',
    categoryEn: 'Invoicing & Tax',
    icon: Building2,
  },
  AUDITOR_REPORT: {
    tabKey: 'AUDITOR_REPORT',
    titleAr: 'تقرير مراقب الحسابات المستقل (معيار 700)',
    titleEn: 'Auditor’s Report (ESA 700)',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: ShieldCheck,
  },
  FINANCIAL_STATEMENTS: {
    tabKey: 'FINANCIAL_STATEMENTS',
    titleAr: 'القوائم المالية الختامية (معيار 1)',
    titleEn: 'Financial Statements (EAS 1)',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: FileSpreadsheet,
  },
  FINANCIAL_NOTES: {
    tabKey: 'FINANCIAL_NOTES',
    titleAr: 'الإيضاحات المتممة للقوائم المالية',
    titleEn: 'Notes to Financial Statements',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: BookOpen,
  },
  FINANCIAL_SIMULATOR: {
    tabKey: 'FINANCIAL_SIMULATOR',
    titleAr: 'محاكي المؤشرات والنسب المالية',
    titleEn: 'Financial Ratios Simulator',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: TrendingUp,
  },
  CREDIT_SIMULATOR: {
    tabKey: 'CREDIT_SIMULATOR',
    titleAr: 'محاكي الجدارة والملف الائتماني',
    titleEn: 'Credit Rating Simulator',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: TrendingUp,
  },
  FRAUD_AUDIT_SENTINEL: {
    tabKey: 'FRAUD_AUDIT_SENTINEL',
    titleAr: 'حارس الفحص الإحصائي وكشف الاحتيال',
    titleEn: 'Fraud Sentinel',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: ShieldCheck,
  },
  AUDIT_WORKING_PAPERS: {
    tabKey: 'AUDIT_WORKING_PAPERS',
    titleAr: 'أوراق عمل الفحص والمراجعة المهنية',
    titleEn: 'Audit Working Papers',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: FileCheck2,
  },
  AUDIT_TRAIL: {
    tabKey: 'AUDIT_TRAIL',
    titleAr: 'سجل العمليات والأمان المالي الرقمي',
    titleEn: 'Audit Trail & Security',
    categoryAr: 'المراجعة والتقارير',
    categoryEn: 'Audit & Reports',
    icon: Shield,
  },
  CLIENTS_ARCHIVE: {
    tabKey: 'CLIENTS_ARCHIVE',
    titleAr: 'أرشيف العملاء وسجلات الشركات',
    titleEn: 'Clients Archive',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: Building2,
  },
  PRACTICE_MANAGEMENT: {
    tabKey: 'PRACTICE_MANAGEMENT',
    titleAr: 'عقود المراجعة والارتباطات المهنية',
    titleEn: 'Engagements Management',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: BookOpen,
  },
  OFFICE_TREASURY: {
    tabKey: 'OFFICE_TREASURY',
    titleAr: 'خزنة المكتب وحسابات الأتعاب والرسوم',
    titleEn: 'Office Treasury & Fees',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: Building2,
  },
  WHATSAPP_BOT: {
    tabKey: 'WHATSAPP_BOT',
    titleAr: 'مجيب واتساب الذكي لخدمة العملاء',
    titleEn: 'WhatsApp AI Bot',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: Sparkles,
  },
  CUSTOMS_HUB: {
    tabKey: 'CUSTOMS_HUB',
    titleAr: 'منظومة العمليات الجمركية والتكلفة الاستيرادية',
    titleEn: 'Customs & Landed Cost Hub',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: Building2,
  },
  SAP_ERP: {
    tabKey: 'SAP_ERP',
    titleAr: 'منظومة التكامل مع SAP S/4HANA',
    titleEn: 'SAP S/4HANA Integration',
    categoryAr: 'إدارة المكتب والعملاء',
    categoryEn: 'Practice & Clients',
    icon: Layers,
  },
  MOBILE_COMPANION: {
    tabKey: 'MOBILE_COMPANION',
    titleAr: 'المساعد الميداني للهاتف',
    titleEn: 'Mobile Field Companion',
    categoryAr: 'الرئيسية والمؤشرات',
    categoryEn: 'Core Dashboard',
    icon: Smartphone,
  },
};

export function getScreenMetadata(tabKey: string): ScreenMetadata {
  if (SCREEN_METADATA_REGISTRY[tabKey]) {
    return SCREEN_METADATA_REGISTRY[tabKey];
  }
  return {
    tabKey,
    titleAr: tabKey,
    titleEn: tabKey,
    categoryAr: 'شاشات المنظومة',
    categoryEn: 'System Screens',
    icon: Folder,
  };
}
